### PR TITLE
Add in unit test of text tracking showing problems with text tracking

### PR DESCRIPTION
**Pull request by seamuslee001**
@totten i am expecting this will fail but it does show that for 2 of the tests the text tracking can be problematic in flexmailer i am having thoughts on how to resolve

### CODE REVIEW

**Comment by totten** [comment]
Looks like tests pass both locally and in CI. @seamuslee001 do you want to do some more confirmation of the regex change? 

(From my POV, we're ok to merge.)

**Comment by seamuslee001** [comment]
@totten good to merge IMO

**Comment by totten** [comment]
Merged and tagged as v1.1.1

**Pull request merged**
